import pygame

# Grid dimensions
BUBBLE_SIZE = 80
BUBBLE_SPACE = 16
GRID_WIDTH = 17
GRID_HEIGHT = 17
GAME_OVER_GRID_HEIGHT = 16
INIT_HEIGHT = 9
SHOW_STATS = True

SCREEN_WIDTH = (BUBBLE_SIZE + BUBBLE_SPACE // 2) * GRID_WIDTH + BUBBLE_SIZE // 2 + BUBBLE_SPACE
SCREEN_HEIGHT = (BUBBLE_SIZE + BUBBLE_SPACE // 2) * GRID_HEIGHT

# Number of shots before a new row advances, cycling through this list each step
TRIES = [5, 4, 3, 2, 1, 0]

# Colors
BACKGROUND = (160, 192, 255)
PURPLE = (101, 35, 148)
BLUE = (1, 154, 255)
PINK = (249, 115, 223)
RED = (255, 20, 20)
GREEN = (101, 255, 1)
ORANGE = (254, 183, 42)
GREY = (200, 200, 200)

PREVIEW_BUBBLE_X = SCREEN_WIDTH // 2
PREVIEW_BUBBLE_Y = SCREEN_HEIGHT - BUBBLE_SIZE - BUBBLE_SPACE

# Custom events
GAME_OVER_EVENT = pygame.USEREVENT
STATE_CHANGE_EVENT = pygame.USEREVENT + 1
TRAVERSE_EVENT = pygame.USEREVENT + 2

DEBUG = False

# Bubble colors
COLORS = [PINK, RED, PURPLE, BLUE, GREEN, ORANGE]
